---
jobs:
  convco_check_job:
    name: Validate Conventional Commit Compliance
    runs-on: ubuntu-latest
    steps:
    - name: Must be Conventional Commit
      uses: gsactions/commit-message-checker@v2
      with:
        error: 'Commit does not comply with Conventional Commit rules'
        pattern: '^(?<type>fix|feat|docs|chore)(?<subject>:\s.*)'
    - name: Contains Azure Board work item reference
      uses: gsactions/commit-message-checker@v2
      with:
        error: 'Commit message does not contain Azure Board work item reference'
        flags: 'gm'
        pattern: 'AB\#[0-9]+'
  markdown:
    name: Validate Markdown Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: markdownlint-cli2-action
      uses: DavidAnson/markdownlint-cli2-action@v11.0.0
      with:
        globs: |
          **/*.md
  yaml-lint:
    name: Lint YAML files
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: yamllint
      uses: karancode/yamllint-github-action@v2.1.1
      with:
        yamllint_comment: true
        yamllint_config_filepath: .yamllint
name: 🕵️ Test
'on': [push]
